# CUSTOMER CHURN PREDICTION fOR IBM (TELECOMMUNICATIONS COMPANY)

# 1.0 BUSINESS UNDERSTANDING

## 1.1 PROBLEM STATEMENT

IBM wants to reduce customer churn by identifting customers who are likely to leave. High churn rates reduce revenue, increase customer acqusition costs and hinder business growth.
IBM has historical customer data containing demographics, contract types, internet services, payment, tenure, monthly charges and churn status. 
The management needs a predictive system that can flag customers ar risk of churning so they can intervene with retention strategies.

## 1.2 BUSINESS QUESTION

- Can a machine learning be used to predict whether a customer will churn based on their characteristics and service information?

## 1.3 OBJECTIVES

**Main objective**: To develop a predictive model that accurately predicts a customer to churn and deploy it.

- Other objectives are; Conduct an in-depth analysis of the dataset to identify key features that impact customers churning in IBM.

# 2.0 UNDERSTANDING THE DATASET(CSV FILE)

The dataset contains historical customer information from IBM company. Each row represents a customer and each column represents a customer attribute such as:

- Demographics (gender, senior citizen, partner, dependents)

- Contract type (month-to-month, one year, two year)

- Internet service (DSL, fiber optic, none)

- Payment method (electronic check, mailed check, bank transfer, credit card)

- Tenure (number of months with the company)

- Monthly charges and total charges

- Subscribed services (online security, tech support, streaming TV, etc.)

- Churn status (target variable: Yes/No)

## 2.1 Imports needed

In [1]:
# imports needed for the project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

## 2.3 Inspect and  Load the dataset

In [2]:
# load the dataset
df_raw = pd.read_csv("IBM Telco Customer churn.csv") # the original dataset
df = df_raw.copy() # data to use for analysis
display(df_raw.head())
display(df_raw.tail())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [3]:
# Check the shape of the dataset
print(f'The dataset has  {df.shape[0]} rows and {df.shape[1]} columns')

The dataset has  7043 rows and 21 columns

In [4]:
# check column types
print("\n=== Column Types ===")
print(df.dtypes)

=== Column Types ===
customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [ ]:
# Summary of the dataset
# in terms of missing values
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

- The dataset has 7043 rows and 21 columns.
- The dataset has no duplicates 
- It has no missing values 
- It has 3 numerical columns 
- It has 9 categorical columns
- Though some data columns has unfit data types like *Total charges* which should be a numerical data type.