# CUSTOMER CHURN PREDICTION fOR IBM (TELECOMMUNICATIONS COMPANY)

# 1.0 BUSINESS UNDERSTANDING

## 1.1 PROBLEM STATEMENT

IBM wants to reduce customer churn by identifting customers who are likely to leave. High churn rates reduce revenue, increase customer acqusition costs and hinder business growth.
IBM has historical customer data containing demographics, contract types, internet services, payment, tenure, monthly charges and churn status. 
The management needs a predictive system that can flag customers ar risk of churning so they can intervene with retention strategies.

## 1.2 BUSINESS QUESTION

- Can a machine learning be used to predict whether a customer will churn based on their characteristics and service information?

## 1.3 OBJECTIVES

**Main objective**: To develop a predictive model that accurately predicts a customer to churn and deploy it.

- Other objectives are; Conduct an in-depth analysis of the dataset to identify key features that impact customers churning in IBM.

# 2.0 UNDERSTANDING THE DATASET(CSV FILE)

The dataset contains historical customer information from IBM company. Each row represents a customer and each column represents a customer attribute such as:

- Demographics (gender, senior citizen, partner, dependents)

- Contract type (month-to-month, one year, two year)

- Internet service (DSL, fiber optic, none)

- Payment method (electronic check, mailed check, bank transfer, credit card)

- Tenure (number of months with the company)

- Monthly charges and total charges

- Subscribed services (online security, tech support, streaming TV, etc.)

- Churn status (target variable: Yes/No)

## 2.1 Imports needed

In [15]:
# ! pip install -r requirements.txt

In [16]:
# imports needed for the project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# suppress warnings for cleaner output
import warnings
warnings.filterwarnings('ignore')

## 2.3 Inspect and  Load the dataset

In [17]:
# load the dataset
df_raw = pd.read_csv("IBM Telco Customer churn.csv") # the original dataset
df = df_raw.copy() # data to use for analysis
display(df_raw.head())
display(df_raw.tail())

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [18]:
# Check the shape of the dataset
print(f'The dataset has  {df.shape[0]} rows and {df.shape[1]} columns')

The dataset has  7043 rows and 21 columns

In [19]:
# check column types
print("\n=== Column Types ===")
print(df.dtypes)

=== Column Types ===
customerID              str
gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges            str
Churn                   str
dtype: object

In [20]:
# describe the dataset numerically 
print("\n=== Dataset Description ===")
display(df.describe())

# describe the dataset categorically
print("\n=== Categorical Description ===")
display(df.describe(include='object'))

=== Dataset Description ===

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

=== Categorical Description ===

,customerID,gender,Partner,Dependents,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,TotalCharges,Churn
count,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043,7043
unique,7043,2,2,2,2,3,3,3,3,3,3,3,3,3,2,4,6531,2
top,7590-VHVEG,Male,No,No,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,20.2,No
freq,1,3555,3641,4933,6361,3390,3096,3498,3088,3095,3473,2810,2785,3875,4171,2365,11,5174

In [21]:
# Summary of the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [22]:
# check for duplicates 
n_dupes = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {n_dupes}")

Number of duplicate rows: 0

In [23]:
# The target variable is 'Churn', which indicates whether a customer has churned or not. Let's check the distribution of this variable.
print("\n=== Churn Distribution ===")
churn_counts = df['Churn'].value_counts() * 100 / len(df)
print(churn_counts)

=== Churn Distribution ===
Churn
No     73.463013
Yes    26.536987
Name: count, dtype: float64

- The dataset has 7043 rows and 21 columns.
- The dataset has no duplicates 
- It has no missing values 
- It has 3 numerical columns 
- It has 9 categorical columns
- Though some data columns has unfit data types like *Total charges* which should be a numerical data type(int64).
- Senior_citizen is also encode hence it being a categorical feature(0 not bieng a senior citizen, 1 being senior citizen).
- The target variable(Churn) is a string/object and the is an imbalance whereby 73% of the customers do not churn while 26% of the customers want to leave.
- The customer ID for prediction because it behaves as index doesn't really influence the target variable in any way( should be dropped).

# 3.0 DATA PREPARATION  AND CLEANING

In [24]:
# correct data type for 'TotalCharges' column
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')

In [25]:
# check missing values
df.isna().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [26]:
# drop the missing values in Total charges 
df = df.dropna()
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [27]:
# check for duplicates 
n_dupes = df.duplicated().sum()
print(f"\nNumber of duplicate rows: {n_dupes}")

Number of duplicate rows: 0

In [31]:
# Define X and y as Features and target 
X = df.drop(['Churn','customerID'], axis= 1) # Features
y = df['Churn'] # target variable

In [32]:
# convert target variable using mapping 
y = y.map({"No":0, "Yes": 1})

In [33]:
# feature
display(X.head())

# Target Variable
display(y.head())

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

# 4.0 Encoding Categorical Features